import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Session, Subject } from '../types';
import { format, startOfMonth, endOfMonth, eachDayOfInterval } from 'date-fns';

export interface ExportOptions {
  startDate?: Date;
  endDate?: Date;
  includeCharts?: boolean;
}

export function exportToPDF(
  sessions: Session[],
  subjects: Subject[],
  options: ExportOptions = {}
) {
  const doc = new jsPDF();
  const { startDate, endDate } = options;

  // Filter sessions by date range if provided
  let filteredSessions = sessions;
  if (startDate && endDate) {
    filteredSessions = sessions.filter(s => {
      const sessionDate = new Date(s.date);
      return sessionDate >= startDate && sessionDate <= endDate;
    });
  }

  // Title
  doc.setFontSize(24);
  doc.setTextColor(79, 70, 229); // Indigo
  doc.text('FocusFlow Study Report', 14, 20);

  // Date range
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const dateRangeText = startDate && endDate
    ? `${format(startDate, 'MMM d, yyyy')} - ${format(endDate, 'MMM d, yyyy')}`
    : `All Time (${filteredSessions.length} sessions)`;
  doc.text(dateRangeText, 14, 28);

  // Statistics Summary
  const totalMinutes = filteredSessions.reduce((sum, s) => sum + s.durationMinutes, 0);
  const totalHours = Math.floor(totalMinutes / 60);
  const remainingMinutes = totalMinutes % 60;
  const avgRating = filteredSessions.length > 0
    ? (filteredSessions.reduce((sum, s) => sum + (s.rating || 0), 0) / filteredSessions.length).toFixed(1)
    : '0';

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('Summary Statistics', 14, 40);

  doc.setFontSize(10);
  const stats = [
    `Total Study Time: ${totalHours}h ${remainingMinutes}m`,
    `Total Sessions: ${filteredSessions.length}`,
    `Average Rating: ${avgRating} / 5`,
    `Subjects Studied: ${new Set(filteredSessions.map(s => s.subjectId)).size}`
  ];

  stats.forEach((stat, index) => {
    doc.text(stat, 14, 48 + (index * 6));
  });

  // Subject Breakdown
  const subjectStats = subjects.map(subject => {
    const subjectSessions = filteredSessions.filter(s => s.subjectId === subject.id);
    const subjectMinutes = subjectSessions.reduce((sum, s) => sum + s.durationMinutes, 0);
    const subjectHours = Math.floor(subjectMinutes / 60);
    const subjectRemainingMinutes = subjectMinutes % 60;
    
    return {
      name: subject.name,
      sessions: subjectSessions.length,
      time: `${subjectHours}h ${subjectRemainingMinutes}m`,
      avgRating: subjectSessions.length > 0
        ? (subjectSessions.reduce((sum, s) => sum + (s.rating || 0), 0) / subjectSessions.length).toFixed(1)
        : 'N/A'
    };
  }).filter(s => s.sessions > 0);

  doc.setFontSize(12);
  doc.text('Subject Breakdown', 14, 80);

  autoTable(doc, {
    startY: 85,
    head: [['Subject', 'Sessions', 'Total Time', 'Avg Rating']],
    body: subjectStats.map(s => [s.name, s.sessions.toString(), s.time, s.avgRating]),
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229] },
    styles: { fontSize: 9 }
  });

  // Session History
  const finalY = (doc as any).lastAutoTable.finalY || 120;
  
  doc.setFontSize(12);
  doc.text('Session History', 14, finalY + 10);

  const sessionData = filteredSessions
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
    .slice(0, 50) // Limit to 50 most recent sessions
    .map(session => {
      const subject = subjects.find(s => s.id === session.subjectId);
      const hours = Math.floor(session.durationMinutes / 60);
      const mins = session.durationMinutes % 60;
      const duration = hours > 0 ? `${hours}h ${mins}m` : `${mins}m`;
      
      return [
        format(new Date(session.date), 'MMM d, yyyy'),
        subject?.name || 'Unknown',
        session.topic || '-',
        duration,
        '⭐'.repeat(session.rating || 0)
      ];
    });

  autoTable(doc, {
    startY: finalY + 15,
    head: [['Date', 'Subject', 'Topic', 'Duration', 'Rating']],
    body: sessionData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] },
    styles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 30 },
      1: { cellWidth: 35 },
      2: { cellWidth: 60 },
      3: { cellWidth: 25 },
      4: { cellWidth: 30 }
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by FocusFlow on ${format(new Date(), 'MMM d, yyyy')} - Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // Save the PDF
  const fileName = startDate && endDate
    ? `FocusFlow_Report_${format(startDate, 'yyyy-MM-dd')}_to_${format(endDate, 'yyyy-MM-dd')}.pdf`
    : `FocusFlow_Report_${format(new Date(), 'yyyy-MM-dd')}.pdf`;
  
  doc.save(fileName);
}

